from config.training_setup import experiments_data, training_configs
from config.training_setup_custom import experiments_data, training_configs #using custom datasets for training (other than rnakinet publication datasets)
from config.evaluation_setup import models_data, exp_groups, pos_neg_pairs, comparison_groups, model_comparison_groups, condition_control_pairs, pooling, datastats_groups

include: "rules/basecalling.smk"
include: "rules/alignment.smk"
include: "rules/data_split.smk"
include: "rules/inference.smk"
include: "rules/visualizations.smk"
include: "rules/diff_exp.smk"
include: "rules/training.smk"


#set the training_experiment_name to the named configuration from training_configs
rule all:
    input:
        expand('checkpoints_pl/{training_experiment_name}/DONE.txt', training_experiment_name='test_run')
        