from config.training_setup import experiments_data, training_configs
from config.evaluation_setup import models_data, exp_groups, pos_neg_pairs, comparison_groups, model_comparison_groups, condition_control_pairs, pooling, datastats_groups

include: "rules/basecalling.smk"
include: "rules/alignment.smk"
include: "rules/data_split.smk"
include: "rules/inference.smk"
include: "rules/visualizations.smk"
include: "rules/diff_exp.smk"
include: "rules/training.smk"

rule all:
    input:
        expand('outputs/visual/predictions/rnakinet/max_ALL_DONE.txt'),